### ISSUE TITLE
[a,b] concatenation is deprecated

### ISSUE THREAD

**Issue by cormullion** [JuliaGraphics/Colors.jl#12] opened 2015-09-01 10:39 UTC
I'm seeing loads of these (my terminal's overflowing with warnings...:)):

    WARNING: [a,b] concatenation is deprecated; use [a;b] instead
     in depwarn at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
     in oldstyle_vcat_warning at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
     in diverging_palette at /Users/cormullion/.julia/v0.4/Colors/src/colormaps.jl:234
     in include at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
     in include_from_node1 at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
     in include at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
     in include_from_node1 at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib

I think it's here:

    if isodd(N)
        midcol = weighted_color_mean(0.5, pal1[end], pal2[1])
        return [pal1[1:end-1]; midcol; pal2[2:end]]
    else
        return [pal1[1:end-1]; pal2[2:end]]
    end

What's the fix - `return collect(pal1[1:end-1]; midcol; pal2[2:end])`?

**Comment by SimonDanisch** [comment] 2015-09-01 10:58
Wasn't this fixed on master by #9 !?
I can't reproduce it anymore with `diverging_palette(0, 360)`
Maybe time to tag?!

**Comment by cormullion** [comment] 2015-09-01 13:41
Yes, I appear to have an older version, despite running  `Pkg.update()`:

`- Colors                        0.5.2`

In my directory I've got:

.julia/v0.4/Colors/src/colormaps.jl

where it says:
    if isodd(N)
        midcol = weighted_color_mean(0.5, pal1[end], pal2[1])
        return [pal1[1:end-1], midcol, pal2[2:end]]
    else
        return [pal1[1:end-1], pal2[2:end]]
    end

which doesn't match the current version.

Sorry for the noise. :)

**Closed** 2015-09-28 12:02 UTC
