### ISSUE TITLE
Not work on Ubuntu 2004

### ISSUE THREAD

**Issue by kongdd** [JuliaGraphics/Colors.jl#471] opened 2021-04-14 05:23 UTC
```julia
using Colors
[ Info: Precompiling Colors [5ae59095-9a9b-59fe-a467-6f913c188581]

signal (11): Segmentation fault
in expression starting at /home/kong/.julia/packages/Colors/hpqjg/src/conversions.jl:656
dswap_k_SKYLAKEX at /usr/lib/x86_64-linux-gnu/liblapack.so.3 (unknown line)
Allocations: 1307989 (Pool: 1307195; Big: 794); GC: 2
ERROR: Failed to precompile Colors [5ae59095-9a9b-59fe-a467-6f913c188581] to /home/kong/.julia/compiled/v1.6/Colors/jl_y3afN0.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::Base.TTY, internal_stdout::Base.TTY)
   @ Base ./loading.jl:1360
 [3] compilecache(pkg::Base.PkgId, path::String)
   @ Base ./loading.jl:1306
 [4] _require(pkg::Base.PkgId)
   @ Base ./loading.jl:1021
 [5] require(uuidkey::Base.PkgId)
   @ Base ./loading.jl:914
 [6] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:901
```

**Comment by johnnychen94** [comment] 2021-04-14 05:30
Could you provide more information of your Julia installation? For example, the result of `versioninfo()`, and how did you install Julia?

**Comment by kongdd** [comment] 2021-04-14 05:35
Sure. 
Julia is installed by unziping the official file `julia-1.6.0-linux-x86_64.tar.gz`.
```julia
versioninfo()
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) W-2145 CPU @ 3.70GHz
  WORD_SIZE: 64    
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake-avx512)
Environment:
  JULIA_NUM_THREADS = 4
  JULIA_PKG_SERVER = https://mirrors.bfsu.edu.cn/julia/static

(@v1.6) pkg> st
      Status `~/.julia/environments/v1.6/Project.toml`
  [5ae59095] Colors v0.12.7
  [91a5bcdd] Plots v1.11.2
```

By the way, the information of `liblapack` on the system:
```bash
sudo apt install libatlas-base-dev liblapack-dev libblas-dev
[sudo] password for kong:
Reading package lists... Done
Building dependency tree
Reading state information... Done
libblas-dev is already the newest version (3.9.0-1build1).
liblapack-dev is already the newest version (3.9.0-1build1).
libatlas-base-dev is already the newest version (3.10.3-8ubuntu7).
libatlas-base-dev set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.


ll /usr/lib/x86_64-linux-gnu/*lapack*
lrwxrwxrwx 1 root root   46 Apr 14 13:19 /usr/lib/x86_64-linux-gnu/liblapack.a -> /etc/alternatives/liblapack.a-x86_64-linux-gnu
lrwxrwxrwx 1 root root   47 Apr 14 13:19 /usr/lib/x86_64-linux-gnu/liblapack.so -> /etc/alternatives/liblapack.so-x86_64-linux-gnu
lrwxrwxrwx 1 root root   49 Aug  5  2020 /usr/lib/x86_64-linux-gnu/liblapack.so.3 -> /etc/alternatives/liblapack.so.3-x86_64-linux-gnu
-rw-r--r-- 1 root root 1.1M Mar 26  2020 /usr/lib/x86_64-linux-gnu/liblapack_atlas.a
lrwxrwxrwx 1 root root   25 Mar 26  2020 /usr/lib/x86_64-linux-gnu/liblapack_atlas.so -> liblapack_atlas.so.3.10.3
lrwxrwxrwx 1 root root   25 Mar 26  2020 /usr/lib/x86_64-linux-gnu/liblapack_atlas.so.3 -> liblapack_atlas.so.3.10.3
-rw-r--r-- 1 root root 371K Mar 26  2020 /usr/lib/x86_64-linux-gnu/liblapack_atlas.so.3.10.3
-rw-r--r-- 1 root root  13M Mar 21  2020 /usr/lib/x86_64-linux-gnu/liblapack_pic.a

/usr/lib/x86_64-linux-gnu/lapack:
total 19M
-rw-r--r-- 1 root root  13M Mar 21  2020 liblapack.a
lrwxrwxrwx 1 root root   18 Mar 21  2020 liblapack.so -> liblapack.so.3.9.0
lrwxrwxrwx 1 root root   18 Mar 21  2020 liblapack.so.3 -> liblapack.so.3.9.0
-rw-r--r-- 1 root root 6.7M Mar 21  2020 liblapack.so.3.9.0
```

**Comment by johnnychen94** [comment] 2021-04-14 05:44
I cannot reproduce this. It's likely to be a local issue. Maybe you can try it again with a new depot path

```console
JULIA_DEPOT_PATH=$HOME/.julia.tmp julia
```

and see it still segfaults.

**Comment by johnnychen94** [comment] 2021-04-14 05:51
`Colors.jl` does not require any binary artifacts related to LAPACK, so this is certainly some issue of your local environment, or somewhere in the upstream Julia.

I'm closing this because it's not a `Colors.jl` issue. But feel free to update it if you still have questions.

**Closed by johnnychen94** 2021-04-14 05:51 UTC

**Comment by kongdd** [comment] 2021-04-14 05:58
Thank you
