### ISSUE TITLE
How to convert to float? / add standard convert methods?

### ISSUE THREAD

**Issue by tbenst** [JuliaGraphics/Colors.jl#447] opened 2020-10-21 19:45 UTC
I don't know how to convert a RGB to a tuple of UInts/Ints/floats, and it's surprisingly hard to figure this out. I don't see it documented, and when I try to find pertinent methods: `methodswith(typeof(RGB{N0f8}(100/255,2/255,20/255)), supertypes=true)`, I get promising hits like `float64` and these convert methods:
```
[85] convert(::Type{C}, c::Color, alpha) where C<:TransparentColor in ColorTypes at /home/tyler/.julia/packages/ColorTypes/RF8lb/src/conversions.jl:78
[86] convert(::Type{C}, c::C) where C<:Colorant in ColorTypes at /home/tyler/.julia/packages/ColorTypes/RF8lb/src/conversions.jl:72
[87] convert(::Type{C}, c::Colorant) where C<:Colorant in ColorTypes at /home/tyler/.julia/packages/ColorTypes/RF8lb/src/conversions.jl:73
```

`float64` does not return primitive values for example. The closest I've figured out is `reinterpret(UInt8, gray(Gray(RGB{N0f8}(100/255,2/255,20/255))))` but that of course isn't all three channels and seems very hard for such a simple task.

Any tips? And perhaps this should be a feature request too for these convert methods to be added

**Comment by timholy** [comment] 2020-10-21 20:01
Are you using ImageCore? `channelview` and `colorview` are the standard methods for arrays. It also has `rawview` and `normedview`. Docs are at https://juliaimages.org/latest/.

The topic is a bit subtle because we support serveral different representations of AbstractRGB: RGB, BGR, XRGB and RGBX (two ways of padding up to 32 bits, good for GPUs), and RGB24. `reinterpret` takes the bitlevel representation at face value (i.e., storage-order) but constructors decouple representation from meaning. For a single `c::AbstractRGB`, the safest approach is just `(red(c), green(c), blue(c))` because then you're in perfect control of what you get out. See https://github.com/JuliaGraphics/ColorTypes.jl#traits-utility-functions-for-instances-and-types.

**Comment by timholy** [comment] 2020-11-01 14:23
Any further thoughts on this topic @tbenst? Can we close this or is there a specific suggestion for improving the documentation?

**Comment by tbenst** [comment] 2020-11-03 08:51
thank you! `channelview` is close to what I was looking for, but alas this does not work: `channelview(RGB{N0f8}(100/255,2/255,20/255))`, however `channelview([RGB{N0f8}(100/255,2/255,20/255)])` does work. Perhaps it's worth highlighting channelview on the Colors docs? It is indeed nicely documented in ImageCore, although I wonder if it's worthwhile to implement a method for `convert` that just calls `channelview`, maybe with a `copy` since perhaps other beginners might expect this to exist?

**Comment by timholy** [comment] 2020-11-03 09:08
In Julia, it's common that anything called "view" references an AbstractArray.

If you're working with an immutable value (like a single RGB), it's extremely wasteful to first create an array out of it just to do color channel manipulations. Can you describe for me more clearly why you are trying to do it this way? What's bad about

```julia
c = RGB{N0f8}(100/255,2/255,20/255)
t = (red(c), green(c), blue(c))   # tuple form
```

**Comment by tbenst** [comment] 2020-11-03 09:49
The tuple form makes sense! That’s what I was originally looking for—how to get the plain old float values out of RGB. I’m quite used to the opencv/numpy/scikit-image way of doing things and got stuck when summing an image, expecting a float, but getting an RGB.

It’s great that these functions exist, but I’m not sure how I would have discovered the functions `red`, `green` and `blue` without you pointing me to them. Perhaps these could be listed on Construction and Conversion? http://juliagraphics.github.io/Colors.jl/stable/constructionandconversion/

**Comment by timholy** [comment] 2020-11-03 10:31
I linked them in https://github.com/JuliaGraphics/Colors.jl/issues/447#issuecomment-713840599. Maybe the problem is the split between ColorTypes and Colors?

**Comment by tbenst** [comment] 2020-11-03 10:53
Ah indeed, that documents this quite clearly. I see it is also linked at http://juliagraphics.github.io/Colors.jl/stable/#Reexport-1. Maybe a reciprocal link to ColorTypes on this repo’s README? Although seems well-documented and an oversight on my part!

**Closed** 2020-11-03 10:57 UTC
